/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package telas;

import dao.CadastroProdutoDao;
import dao.VendaProdutoDao;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import javax.swing.table.DefaultTableModel;
import model.CadastroProduto;
import model.VendaProduto;

/**
 *
 * @author difoz
 */
public class vendas extends javax.swing.JInternalFrame {
int vInsUpdate = 0;
private CadastroProduto produtoAtual;
    /**
     * Creates new form vendas
     */
    public vendas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtBuscarVenda = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jValorTotal = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTabelaCarrinho = new javax.swing.JTable();
        btnComprar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Buscar");

        txtBuscarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarVendaActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Quantidade", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Valor Total");

        jValorTotal.setEditable(false);
        jValorTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTabelaCarrinho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Quantidade", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTabelaCarrinho);
        if (jTabelaCarrinho.getColumnModel().getColumnCount() > 0) {
            jTabelaCarrinho.getColumnModel().getColumn(0).setResizable(false);
            jTabelaCarrinho.getColumnModel().getColumn(1).setResizable(false);
            jTabelaCarrinho.getColumnModel().getColumn(2).setResizable(false);
            jTabelaCarrinho.getColumnModel().getColumn(3).setResizable(false);
        }

        btnComprar.setText("Comprar");
        btnComprar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnComprarMouseClicked(evt);
            }
        });

        btnCancelar.setText("Cancelar Compra");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnComprar)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComprar)
                    .addComponent(btnCancelar))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarVendaActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       if((jTable1.getSelectedRow() != -1) && (vInsUpdate == 0) && (evt.getClickCount() == 2)){
        // Pega os dados da linha selecionada
        String idProduto = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
        String nomeProduto = jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString();
        String valorProduto = jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString();
        String estoqueDisponivel = jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString();

        // Abre um diálogo para o usuário inserir a quantidade desejada
        String quantidadeCompra = JOptionPane.showInputDialog(this, "Digite a quantidade desejada:", "Quantidade", JOptionPane.PLAIN_MESSAGE);
        
        // Verifica se a quantidade foi inserida e se é válida
        if (quantidadeCompra != null && !quantidadeCompra.isEmpty()) {
            try {
                // Verifica se a quantidade inserida é um número inteiro
                int quantidade = Integer.parseInt(quantidadeCompra);
                int estoque = Integer.parseInt(estoqueDisponivel);
                
                // Verifica se a quantidade desejada está disponível no estoque
                if (quantidade > 0 && quantidade <= estoque) {
                    // Calcula o valor total para o item
                    double valorUnitario = Double.parseDouble(valorProduto.replace(",", "."));
                    double valorTotal = valorUnitario * quantidade;

                    // Adiciona o item na outra tabela (exemplo: jTable2)
                    DefaultTableModel modeloTabelaCompra = (DefaultTableModel) jTabelaCarrinho.getModel();
                    modeloTabelaCompra.addRow(new Object[]{
                        idProduto,
                        nomeProduto,
                        quantidade,
                        valorTotal
                    });
                    
                    // Atualiza o valor total após adicionar o item
                    atualizaValorTotal();

                    // Armazena informações do produto para uso posterior
                    this.produtoAtual = new CadastroProduto();
                    produtoAtual.setIdProduto(Integer.parseInt(idProduto));
                    produtoAtual.setNome(nomeProduto);
                    produtoAtual.setQuantidade(estoque - quantidade); // Novo estoque, mas ainda não atualizado no banco
                    produtoAtual.setValor(valorUnitario);
                } else {
                    JOptionPane.showMessageDialog(this, "Quantidade solicitada inválida ou maior que o estoque disponível!", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            } catch (NumberFormatException e) {
                // Trata a exceção caso o valor inserido não seja um número inteiro
                JOptionPane.showMessageDialog(this, "Por favor, insira um número válido para a quantidade!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
         limparTabelaCarrinho(); // Chama o método para limpar a tabela e o total
    JOptionPane.showMessageDialog(this, "Carrinho limpo!", "Cancelar", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnComprarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprarMouseClicked
       if (this.produtoAtual != null) {
        CadastroProdutoDao updateDao = new CadastroProdutoDao();
        updateDao.alterar(produtoAtual);
        
        // Atualiza o estoque na tabela
        jTable1.setValueAt(produtoAtual.getQuantidade(), jTable1.getSelectedRow(), 2);
        
        VendaProduto venda = new VendaProduto();
        venda.setQuantVendida(produtoAtual.getQuantidade()); // Defina a quantidade vendida
        venda.setValorTotal(atualizaValorTotal()); // Supondo que você tenha um método para calcular o valor total
        venda.setIdProduto(produtoAtual.getIdProduto()); // Supondo que o ID do produto esteja disponível em produtoAtual

        // Insere a venda no banco de dados
        VendaProdutoDao vendaDao = new VendaProdutoDao();
        vendaDao.inserir(venda);
        
        JOptionPane.showMessageDialog(this, "Compra realizada com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        
        // Limpa a referência do produto atual após a compra
        this.produtoAtual = null;
        limparTabelaCarrinho(); // Chama o método para limpar a tabela e o total
        JOptionPane.showMessageDialog(this, "Carrinho limpo!", "Cancelar", JOptionPane.INFORMATION_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(this, "Selecione um produto e adicione ao carrinho antes de comprar.", "Aviso", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_btnComprarMouseClicked
public void atualizaTabela (CadastroProdutoDao cadastroProd)
    {
        

                try
                {
                    limparTabela();
                    ArrayList<model.CadastroProduto> listaCadastros;
                    listaCadastros = cadastroProd.consultar();      
                    DefaultTableModel modeloTabela = (DefaultTableModel) jTable1.getModel();

                    for(model.CadastroProduto cadastroP : listaCadastros)
                    {
                        modeloTabela.addRow(new String[]{Integer.toString(cadastroP.getIdProduto()), 
                                                                            cadastroP.getNome(), 
                                                                            String.valueOf(cadastroP.getQuantidade()), 
                                                                            String.valueOf(cadastroP.getValor())});
                    }

                }
                catch(Exception ex)
                {
                    JOptionPane.showMessageDialog(null, "Ocorreu um erro inesperado:\n" + ex.getMessage(), "ERRO!", ERROR_MESSAGE);
                }
     
    }

public void limparTabela()
    {
        while(jTable1.getRowCount() > 0) 
        {
            DefaultTableModel dm = (DefaultTableModel) jTable1.getModel();
            dm.getDataVector().removeAllElements();
        }
    }
public void limparTabelaCarrinho() {
    DefaultTableModel modeloCarrinho = (DefaultTableModel) jTabelaCarrinho.getModel();
    modeloCarrinho.setRowCount(0); // Limpa todas as linhas da tabela de carrinho

    // Limpa o campo de valor total (assumindo que jValorTotal é um JTextField)
    jValorTotal.setText("0.00"); // Ou o valor padrão que você deseja mostrar
}

private double  atualizaValorTotal() {
    double total = 0.0;
    DefaultTableModel modeloTabela2 = (DefaultTableModel) jTabelaCarrinho.getModel();

    // Itera por todas as linhas da tabela para somar os valores da coluna de valor total
    for (int i = 0; i < modeloTabela2.getRowCount(); i++) {
        // Pega o valor da coluna de valor total (supondo que a coluna 3 seja a coluna de valores)
        Object valorObj = modeloTabela2.getValueAt(i, 3);  // Verifique se a coluna 3 contém os valores

        // Converte o valor para double, se necessário
        if (valorObj instanceof String) {
            try {
                // Substitui vírgulas por pontos caso necessário
                String valorStr = ((String) valorObj).replace(",", ".");
                total += Double.parseDouble(valorStr);
            } catch (NumberFormatException e) {
                // Trata erros de conversão de string para número
                JOptionPane.showMessageDialog(this, "Erro ao calcular o valor total: formato inválido", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else if (valorObj instanceof Number) {
            total += ((Number) valorObj).doubleValue();
        }
    }

    // Formata o valor total para exibir com duas casas decimais
    DecimalFormat df = new DecimalFormat("#,##0.00");
    String valorFormatado = df.format(total);

    // Define o valor formatado no jTextField1
    jValorTotal.setText(valorFormatado);
    return total;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnComprar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTabelaCarrinho;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jValorTotal;
    private javax.swing.JTextField txtBuscarVenda;
    // End of variables declaration//GEN-END:variables
}
